name: "Terraform Validate"

on:
  pull_request:


jobs:
  TerraformValidate: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate -no-color
        